//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        public int ProductID { get; set; }

        [Required(ErrorMessage ="Please enter product name")]
        [Display(Name ="Product Name")]
        [StringLength(50)]
        public string ProductName { get; set; }

        [Display(Name ="Supplier")]
        [Range(10,20)]
        public Nullable<int> SupplierID { get; set; }
        [Display(Name ="Category")]
        [Required]
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    }
}
